.github/workflows/ci-workflow.yml
.github/workflows/obs-publish.yml
tests/test_adapter.py

Add temporary test
This is our standard python project workflows. Added a temp test to get coverage passing

Add workflows for obs publish and CI testing

---

csp_billing_adapter/local_csp.py

Return a random uuid record id

Reduce chance of failure in mock csp billing

---

setup.cfg
tests/data/config_bad.yaml
tests/data/config_good.yaml
tests/unit/test_config.py

This PR adds some basic unit tests for the Config module.

add unit tests for config

---

csp_billing_adapter/memory_cache.py
tests/unit/conftest.py
tests/unit/test_memory_cache.py

Add tests to cover the cache get, update (merge and replace) and save
hooks.
Also implement some rudimentary fixtures to provide config and pm
to tests.

Basic unit testing for the in-memory cache methods.

---

tests/unit/conftest.py

Add support for optionally specifying a config file name, located in the tests/data directory, via a new config marker, defaulting to the 'config_good.yaml` if no marker is specified, which will be loaded and returned as the result of the fixture.
Added a new session scoped 'data_dir' fixture that returns the path to the tests/data directory for the current pytest run.

Enhance cba_config fixture to load an actual config file

---

csp_billing_adapter/utils.py
tests/unit/test_utils.py

This PR cleans up the utils function and also add unit tests
closes #11

cleanup utils and add unit tests

---

csp-billing-adapter.spec

Change to multispec with python 2 disabled.

Cleanup spec file

---

csp_billing_adapter/__init__.py
csp_billing_adapter/adapter.py
csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_cache.py
csp_billing_adapter/csp_config.py
csp_billing_adapter/csp_hookspecs.py
csp_billing_adapter/hookspecs.py
csp_billing_adapter/local_csp.py
csp_billing_adapter/memory_cache.py
csp_billing_adapter/memory_csp_config.py
csp_billing_adapter/product_api.py
csp_billing_adapter/storage_hookspecs.py

Also add missing copyright notics to bill_utils.py

Add missing module level docstrings.

---

csp_billing_adapter/adapter.py
csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_cache.py
csp_billing_adapter/csp_config.py
csp_billing_adapter/csp_hookspecs.py
csp_billing_adapter/hookspecs.py
csp_billing_adapter/local_csp.py
csp_billing_adapter/product_api.py
csp_billing_adapter/storage_hookspecs.py
csp_billing_adapter/utils.py

Also add appropriate return type signatures to most functions.

Add missing docstrings for functions.

---

csp_billing_adapter/bill_utils.py
csp_billing_adapter/local_csp.py
tests/unit/test_local_csp.py

with changes to meter_billing. timestamp is datetime type and added dry_run bool option.

Update local_csp & bill utils

---

csp_billing_adapter/csp_config.py
csp_billing_adapter/csp_hookspecs.py
csp_billing_adapter/local_csp.py
tests/unit/test_local_csp.py

And add example return dict structure for csp get_account_info hook function.

Add csp data to csp config at start time

---

.gitignore

Pulls in:
* https://github.com/github/gitignore/raw/main/Global/Vim.gitignore

Git ignorance support for Vim

---

csp_billing_adapter/config.py
csp_billing_adapter/csp_config.py
csp_billing_adapter/local_csp.py
csp_billing_adapter/memory_cache.py
csp_billing_adapter/memory_csp_config.py
csp_billing_adapter/product_api.py
csp_billing_adapter/utils.py

This included re-working some routines to save the return value to a variable so that it could be logged before returning it.
Also converted Config.parse_value to a standard method so that we can access the associated class object to dynamically retrieve the name, rather than using static references.
Also updated meter_billing() to report the dimensions at info level, and log an explicit warning message when a simulated failure happens.
Simplified docstrings for Config's load_defaults and load_from_file methods.
Implements: #70

Add debug logging to additional modules.

---

csp_billing_adapter/adapter.py
csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_cache.py
csp_billing_adapter/csp_config.py
tests/unit/test_adapter.py
tests/unit/test_csp_cache.py
tests/unit/test_csp_config.py

Usage data will take one cycle to show up

Wait one cycle at startup for usage data

---

README.md

Update README.md to indicate when errors clear.

---

csp_billing_adapter/adapter.py
tests/unit/test_adapter.py

During the initial startup we perform a metering test in an effort to detect deployment failures as early as possible. If this testing encounters an error we should endeavour to update the csp_config to indicate that the error occurred before the adapter process dies.
For the sake of code readability the metering test code has been moved out of the main() routine to a new metering_test() routine.
Updated existing tests to reflect the move of the metering test to the new routine, and added an initial test to validate handling of hook.update_csp_config() failures.
Fixes: #108

Improved initial metering test exception handling

---

csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_cache.py
csp_billing_adapter/csp_hookspecs.py
csp_billing_adapter/local_csp.py
tests/unit/test_adapter.py
tests/unit/test_csp_cache.py

changed meter_billing return from string to list to partially address https://github.com/SUSE-Enceladus/csp-billing-adapter/issues/112

changed meter_billing return

---

csp_billing_adapter/adapter.py
csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_cache.py
csp_billing_adapter/csp_hookspecs.py
csp_billing_adapter/exceptions.py
csp_billing_adapter/local_csp.py
tests/data/config_dimensions_gap.yaml
tests/data/config_invalid_consumption.yaml
tests/data/config_testing_mixed.yaml
tests/unit/test_adapter.py
tests/unit/test_bill_utils.py
tests/unit/test_csp_cache.py
tests/unit/test_local_csp.py

Tracker PR merge staging to main.

Handle multiple billing dimensions and tiered consumption

---

csp_billing_adapter/adapter.py
tests/unit/test_adapter.py

Add tests for update logger level

Add get_logger and logging level

---

CHANGES.md

- Add changes for 0.5.0 created tag
- Add changes for new to be created 0.6.0 tag

Update changelog for v0.6.0

---

examples/README.md
examples/csp-billing-adapter-example-Rancher_NV.yaml
examples/csp-billing-adapter-example-SUMA.yaml
tests/data/config_bad.yaml
tests/data/config_dimensions_gap.yaml
tests/data/config_dimensions_no_tail.yaml
tests/data/config_good_average.yaml
tests/data/config_good_maximum.yaml
tests/data/config_invalid_consumption.yaml
tests/data/config_no_dimensions.yaml
tests/data/config_no_usage_metrics.yaml
tests/data/config_testing_mixed.yaml

This determines the number of months worth of metering data to store in the archive.
Merging to staging branch for the entire data archive feature.

Add archive retention period config option

---

csp_billing_adapter/archive.py
tests/unit/test_archive.py

This includes a data rotation based on max length attr.

Add util function to handle archive update

---

csp-billing-adapter.spec

Switch the build to support multiple Python interpreter versions. For SLE build with Python 3.11. Use wheel build.

Switch build

---

.github/workflows/ci-workflow.yml
tests/unit/test_utils.py

Also, we should be running lint on pull request as well.

Fix CI failures

---

systemd/csp-billing-adapter.service

Billing adapter needs network and uyuni service running

Update systemd unit file

---

.github/workflows/ci-workflow.yml

Drop 3.6 and 3.7 testing

---

csp_billing_adapter/adapter.py
csp_billing_adapter/utils.py
tests/unit/test_utils.py

This is triggered by the flag no_data_query in the api option

Add handling for fixed usage

---

csp_billing_adapter/adapter.py
csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_cache.py
csp_billing_adapter/csp_config.py
csp_billing_adapter/utils.py
tests/data/config_good_fixed.yaml
tests/unit/test_adapter.py
tests/unit/test_bill_utils.py
tests/unit/test_csp_cache.py
tests/unit/test_csp_config.py

And configured end of support dates

Add handling for configured billing dates

---

csp_billing_adapter/adapter.py
csp_billing_adapter/bill_utils.py
csp_billing_adapter/csp_config.py
csp_billing_adapter/local_csp.py

If it exists. If customer billing id is set the adapter uses batch billing for saas products.

Get customer id from environment

---

csp_billing_adapter/utils.py
tests/unit/test_utils.py

If it doesn't already have a timezone

Make the datetime timezone aware
