SUSE-Enceladus/csp-billing-adapter

- CONTRIBUTING.md
- requirements.txt
Add `pyyaml` as a required package in requirements.txt.
Also update the CONTRIBUTING.md to reflect that need for a config
file, ~/.config/csp-billing-adapter.yaml.
Fixes: #23
> The yaml package is required to load the YAML config

- csp_billing_adapter/adapter.py
- csp_billing_adapter/memory_cache.py
Add a new in-memory cache implementation that can be used for basic
testing & verification of the csp-billing-adapter core functionality.
> Add an in-memory cache implementation

- csp_billing_adapter/adapter.py
- csp_billing_adapter/csp_cache.py
- csp_billing_adapter/memory_cache.py
- csp_billing_adapter/storage_hookspecs.py
Update the hook specs and implementations for the update_cache and
update_csp_config hooks to remove the default value for the replace
argument.
Update hook calls to add replace=False where previously the default
value was being relied upon.
Implemenents: #34
> Remove default parameter values in hook specs and impls

- csp_billing_adapter/adapter.py
- csp_billing_adapter/memory_csp_config.py
- tests/unit/conftest.py
- tests/unit/test_memory_csp_config.py
Similarly to the in-memory cache, this allows for functional testing without the need to load additional plugins.
Added unit tests to exercise the in-memory csp_config with the hook interfaces.
> Add in-memory csp_config implementation

- csp_billing_adapter/csp_hookspecs.py
Amazon expects datetime object for timestamp and has a dry_run option that can be passed through for testing.
> Update meter_billing hookspec

- csp_billing_adapter/adapter.py
- tests/test_adapter.py
- tests/unit/conftest.py
- tests/unit/test_adapter.py
- tests/unit/test_bill_utils.py
By refectoring the main() routine to call subroutines for various stages this allows easy unit testing of those stages.
Add unit tests for the new subroutines representing the various stages of the refactored main.
As part of implementing the test for get_config() the a new fixture, cba_config_path, was created to provide access to the marked config path, and the cba_config fixture has been re-worked to leverage it to determine the path to the file to load.
Also added a unit test for main itself to validate correct operation of exception handling.
Moved tests/test_adapter.py into tests/unit.
> Refactor main() into multiple subroutines

- setup.cfg
Also add show_missing=True to setup.cfg options for pytext coverage reporting so that it shows the line numbers for the statements not covered.
> Restore 90% coverage requirement

- csp_billing_adapter/adapter.py
- tests/unit/conftest.py
- tests/unit/test_adapter.py
Move the registration of the last of the testing support plugins, local_csp, to the cba_pm fixture in tests/unit/conftest.py.
Also validate in the get_plugin_manager() testing that none of the testing plugins are loaded by default anymore.
Implements: #62
> Only load testing support plugins in unit tests

- csp_billing_adapter/adapter.py
- csp_billing_adapter/csp_cache.py
- csp_billing_adapter/csp_config.py
- csp_billing_adapter/exceptions.py
- tests/unit/conftest.py
- tests/unit/test_adapter.py
- tests/unit/test_csp_cache.py
- tests/unit/test_csp_config.py
Enhance the exception handling support for code paths related to the the initial start up of the CSP Billing Adapter.
* failures retrieving existing data from data stores that may not exist yet are handled gracefully, without the main event loop seeing them.
* failures creating/initializing key data stores are reported and an exception is raised that will cause the main event loop to fail.
* failures to retrieve usage data, which may not have been published yet, are handled gracefully, skipping follow on metering attempt for now, and without the main event loop seeing them. NOTE: If this issue persists this would lead to metering not being performed, but performing metering would overwrite the error that was reported for the get_usage_data() operation.
Add tests to exercise and validate …
> Initial exception handling enhancements

- setup.cfg
- tests/unit/test_adapter.py
Also add the relevant unittest file to list of files that bumpversion updates.
> Update unittests to match recent bumpversion run.

- csp_billing_adapter/adapter.py
- csp_billing_adapter/config.py
- tests/unit/conftest.py
- tests/unit/test_adapter.py
By factoring in how long the event_loop_handler() processing takes when calculating the amount of time to sleep for, the drift effect will be minimised.
Enable debug level message logging for the cba_log fixture.
Also fixed typo in Config.__init__() log message format that showed up when debug level logging was enabled.
Fixes: #84
> Sleep for the remainder of a query_interval.

- csp_billing_adapter/adapter.py
- csp_billing_adapter/bill_utils.py
- csp_billing_adapter/csp_cache.py
- tests/unit/test_adapter.py
- tests/unit/test_bill_utils.py
- tests/unit/test_csp_cache.py
- Use cache and csp_config in memory
- Pass in now timestamp instead of re-generating
- Save config map and cache once at end of loop
> Handle multiple errors using error list

- csp_billing_adapter/adapter.py
- csp_billing_adapter/bill_utils.py
- csp_billing_adapter/config.py
- csp_billing_adapter/csp_cache.py
- csp_billing_adapter/csp_config.py
- csp_billing_adapter/utils.py
- tests/unit/test_adapter.py
- tests/unit/test_bill_utils.py
- tests/unit/test_csp_cache.py
- tests/unit/test_csp_config.py
- tests/unit/test_utils.py
Add retry_on_exception() which can retry an arbitrary function call, encapsulated as a functools.partial, when an exception occurs.
Wrap all our hook calls with retry_on_exception().
Fix typo in get_now() log call.
Add unit tests for retry_on_exception().
Fixes: #81
> Support retrying functions when exceptions occur.

- csp_billing_adapter/adapter.py
Thus the errors should be debug level. If the adapter is restarted or re-deployed on a cluster where it was already running then the data exists. Both are valid workflows.
> At initial startup on first deploy no data exists

- csp_billing_adapter/adapter.py
And set the time to GMT/UTC to match csp config, usage data and cache.
Fixes #87
> Add timestamp to base logger format

- csp_billing_adapter/adapter.py
- csp_billing_adapter/product_api.py
- tests/unit/test_adapter.py
Each time a usage record is retrieved. This keeps the support config up-to-date with latest product version.
> Add base_product info to csp_config

- csp_billing_adapter/adapter.py
- tests/data/config_no_dimensions.yaml
- tests/data/config_no_usage_metrics.yaml
- tests/unit/test_adapter.py
Add additional tests to cover exception handling scenarios related to:
* update_cache() and update_csp_config() calls at the end of event_loop_handler().
* failure to retrieve required items from the config in main()
Also added an AttributeError handler to the meter_billing() testing in main(), similar to the KeyError one, to catch issues when using attribute lookup to access Config entries.
Added 2 broken test configs with appropriate missing fields to aid in testing the config item retrievals.
> Improve test coverage for exception scenarios.

- csp_billing_adapter/adapter.py
Add missing logger= prefix when passing the log paramter to the retry_on_exception() routine.
Fixes: #99
> Fix retry_on_exception() call parameters

- csp_billing_adapter/adapter.py
- csp_billing_adapter/csp_config.py
- tests/unit/test_adapter.py
- tests/unit/test_bill_utils.py
- tests/unit/test_csp_config.py
The function only creates a new dict and takes account info as a arg. The csp-config is saved to datastore separately from calling scope.
> Split up create_csp_config into components

- .github/workflows/ci-workflow.yml
- CONTRIBUTING.md
- requirements-dev.txt
- tox.ini
Added a tox.ini that defines testing environments for Python versions 3.6 through 3.12 pytest coverage testing, as well as the code quality tests.
This should work with the versions of tox available for actively supported openSUSE, SLE and Ubuntu distributions.
Updated CONTRIBUTING.MD with instructions for how to use tox to drive the tests. Also added some additional verbiage in the initial installation instructions advising how to create a venv.
Updated Github Actions workflows to enable using tox to run the tests.
Relates: #116
> Add support for using tox to run tests.

- csp_billing_adapter/bill_utils.py
- csp_billing_adapter/local_csp.py
- tests/unit/test_bill_utils.py
If the return type for meter billing is a string then assume it is record id and there is only one dimension being billed. Create a billing status dictionary with this information.
Fixes #122 and adds back the final piece to resolve #112.
> Handle legacy meter billing return type

- csp-billing-adapter.spec
For csp-billing-adapter-service, the requirement
can not be satisfied with current name of the package csp-billing-adapter, this works with python3-csp-billing-adapter
> Update requirement to satisfy dependency

- csp_billing_adapter/csp_cache.py
Every billing cycle the records are emptied. Printing "initial" usage record at the beginning of each cycle is confusing.
> Update message when records list is empty

- csp_billing_adapter/adapter.py
- tests/unit/test_adapter.py
Sleeping on a container rollout risks missing usage data.
> Only sleep at initial deployment

- csp_billing_adapter/adapter.py
- csp_billing_adapter/csp_cache.py
- tests/unit/test_adapter.py
- tests/unit/test_bill_utils.py
- tests/unit/test_csp_cache.py
Any record that is older than the current billing period would be orphaned and lead to "memory leak" of cache.
This could happen if the query interval is shorter than the products usage updates. A metered billing could empty the records in cache and the adapter picks up an old usage record before the product cycles.
> Skip invalid records

- README.md
- csp_billing_adapter/adapter.py
- csp_billing_adapter/hookimpls.py
- csp_billing_adapter/hookspecs.py
- csp_billing_adapter/local_csp.py
- tests/unit/test_hookimpls.py
- tests/unit/test_local_csp.py
And an imlementation for core version. Returns a tuple with plugin name and plugin version. Each plugin is expected to implement the hook and all data is aggregated into the external API.
> Add get version hook spec

- csp_billing_adapter/bill_utils.py
Deleting the key does not work during persistence because dictionary merge is used. When merging if the key has been deleted no changes are made to the persisted value.
> Clear billing status with an empty dictionary

- csp_billing_adapter/archive_hookspecs.py
- examples/README.md
To clarify what will be stored in the data archive. This will contain a list of meterings and also the relevant usage records for each metering.
> Cleanup docstring and readme

- csp_billing_adapter/adapter.py
- csp_billing_adapter/archive.py
- csp_billing_adapter/bill_utils.py
- csp_billing_adapter/memory_archive.py
- tests/unit/conftest.py
- tests/unit/test_archive.py
And integrate archive into the adapter event loop. Each billing cycle is archived with metering and usage info included. With a default archive length of 6 months.
> Implement archive record function

- csp_billing_adapter/bill_utils.py
- tests/unit/test_bill_utils.py
But do not re-raise or add error to csp config which marks the adapter as in an unsupported state. Archive failure is not critical.
> Catch and log non-fatal archive error

- README.md
- examples/README.md
And clean up option description for archive values in example config.
> Update readme with details about archive

- README.md
- csp_billing_adapter/adapter.py
- csp_billing_adapter/archive.py
- csp_billing_adapter/archive_hookspecs.py
- csp_billing_adapter/bill_utils.py
- csp_billing_adapter/csp_config.py
- csp_billing_adapter/memory_archive.py
- examples/README.md
- examples/csp-billing-adapter-example-Rancher_NV.yaml
- examples/csp-billing-adapter-example-SUMA.yaml
- tests/data/config_bad.yaml
- tests/data/config_dimensions_gap.yaml
- tests/data/config_dimensions_no_tail.yaml
- tests/data/config_good_average.yaml
- tests/data/config_good_average_no_archive.yaml
- tests/data/config_good_maximum.yaml
- tests/data/config_invalid_consumption.yaml
- tests/data/config_no_dimensions.yaml
- tests/data/config_no_usage_metrics.yaml
- tests/data/config_testing_mixed.yaml
- tests/unit/conftest.py
- tests/unit/test_archive.py
- tests/unit/test_bill_utils.py
- tests/unit/test_csp_config.py
Tracker PR. Merging feature branch to main.
> Add metering archive

- csp-billing-adapter.spec
With the switch to other Python interpreters to build the code the service cannot explicitly depend on the code being built with the Python 3.6 interpreter.
> Fix the dependency of the service subpackage

- README.md
- csp_billing_adapter/utils.py
- tests/unit/test_utils.py
Since Azure only allow submitting usage for no more than once a day, or we'll get a HTTP 400 "Invalid usage state" error. See https://learn.microsoft.com/en-us/partner-center/marketplace-offers/azure-container-metered-billing
Signed-off-by: yeey <gyee@suse.com>
> Support daily billing interval to enable testing on Azure

- csp-billing-adapter.spec
The package builds for python 3.## version instead of only python3
> Add obsoletes to spec file
